[package]
name = "coarsetime"
version = "0.1.6"
description = "Time and duration crate optimized for speed"
authors = ["Frank Denis <github@pureftpd.org>"]
keywords = ["time", "date", "duration"]
readme = "README.md"
license = "ISC"
homepage = "https://github.com/jedisct1/rust-coarsetime"
repository = "https://github.com/jedisct1/rust-coarsetime"
categories = ["concurrency", "date-and-time", "os"]

[badges]
travis-ci = { repository = "jedisct1/rust-coarsetime" }
appveyor = { repository = "jedisct1/rust-coarsetime" }


[dependencies]
clippy = {version = ">=0", optional = true}
lazy_static = "~1"
libc = "~0.2"

[profile.release]
lto = true
panic = "abort"
opt-level = 3
